dist: trusty

before_install:
    - wget https://archive.apache.org/dist/tinkerpop/3.3.2/apache-tinkerpop-gremlin-server-3.3.2-bin.zip
    - unzip apache-tinkerpop-gremlin-server-3.3.2-bin.zip
    - export GREMLIN_SERVER=${TRAVIS_BUILD_DIR}/apache-tinkerpop-gremlin-server-3.3.2

install:
    - go get github.com/golang/dep/cmd/dep
    - dep ensure

script:
    - go test -v ./...
    - cd ${TRAVIS_BUILD_DIR}/gremlin-sync
    - go build -v
    - cd ${TRAVIS_BUILD_DIR}/gremlin-probe
    - go build -v
    - cd ${TRAVIS_BUILD_DIR}/gremlin-dump
    - go build -v
    - cd ${TRAVIS_BUILD_DIR}/gremlin-neutron
    - go build -v
    - cd ${TRAVIS_BUILD_DIR}

after_success:
    - echo "Pushing binaries to contrail-gremlin-binaries repo"
    - export BINARIES_REPO=https://eonpatapon:${GITHUB_TOKEN}@github.com/eonpatapon/contrail-gremlin-binaries
    - export COMMIT_ID=$(git rev-parse HEAD)
    - git clone -q ${BINARIES_REPO}
    - cd contrail-gremlin-binaries
    - git checkout -B ${TRAVIS_BRANCH} --track origin/${TRAVIS_BRANCH} || git checkout -b ${TRAVIS_BRANCH}
    - cd ${TRAVIS_BUILD_DIR}
    - cp ${TRAVIS_BUILD_DIR}/gremlin-sync/gremlin-sync ${TRAVIS_BUILD_DIR}/contrail-gremlin-binaries
    - cp ${TRAVIS_BUILD_DIR}/gremlin-probe/gremlin-probe ${TRAVIS_BUILD_DIR}/contrail-gremlin-binaries
    - cp ${TRAVIS_BUILD_DIR}/gremlin-dump/gremlin-dump ${TRAVIS_BUILD_DIR}/contrail-gremlin-binaries
    - cp ${TRAVIS_BUILD_DIR}/gremlin-neutron/gremlin-neutron ${TRAVIS_BUILD_DIR}/contrail-gremlin-binaries
    - cd ${TRAVIS_BUILD_DIR}/contrail-gremlin-binaries
    - git add .
    - git -c user.name='Travis' -c user.email='Travis' commit -m "contrail-gremlin commit ${COMMIT_ID}"
    - git push -f origin ${TRAVIS_BRANCH}

language: go
go:
    - 1.10.x
