dist: trusty

before_install:
    - wget https://archive.apache.org/dist/tinkerpop/3.3.1/apache-tinkerpop-gremlin-server-3.3.1-bin.zip
    - unzip apache-tinkerpop-gremlin-server-3.3.1-bin.zip
    - cp ${TRAVIS_BUILD_DIR}/conf/* ${TRAVIS_BUILD_DIR}/apache-tinkerpop-gremlin-server-3.3.1/conf
    - cd ${TRAVIS_BUILD_DIR}/apache-tinkerpop-gremlin-server-3.3.1
    - bin/gremlin-server.sh conf/gremlin-server-contrail.yaml 2>&1 > /dev/null &
    - cd ${TRAVIS_BUILD_DIR}

install:
    - go get github.com/golang/dep/cmd/dep
    - go get github.com/kardianos/govendor

script:
    - cd ${TRAVIS_BUILD_DIR}/gremlin-sync
    - govendor sync
    - go get -t -v ./...
    - go test -v ./...
    - go build -v
    - cd ${TRAVIS_BUILD_DIR}/gremlin-probe
    - go get -t -v ./...
    - go build -v
    - cd ${TRAVIS_BUILD_DIR}/gremlin-dump
    - dep ensure
    - go build -v
    - cd ${TRAVIS_BUILD_DIR}

after_success:
    - echo "Pushing binaries to contrail-gremlin-binaries repo"
    - export BINARIES_REPO=https://eonpatapon:${GITHUB_TOKEN}@github.com/eonpatapon/contrail-gremlin-binaries
    - export COMMIT_ID=$(git rev-parse HEAD)
    - git clone -q ${BINARIES_REPO}
    - cd contrail-gremlin-binaries
    - git checkout -B ${TRAVIS_BRANCH} --track origin/${TRAVIS_BRANCH} || git checkout -b ${TRAVIS_BRANCH}
    - cd ${TRAVIS_BUILD_DIR}
    - cp ${TRAVIS_BUILD_DIR}/gremlin-sync/gremlin-sync ${TRAVIS_BUILD_DIR}/contrail-gremlin-binaries
    - cp ${TRAVIS_BUILD_DIR}/gremlin-probe/gremlin-probe ${TRAVIS_BUILD_DIR}/contrail-gremlin-binaries
    - cp ${TRAVIS_BUILD_DIR}/gremlin-dump/gremlin-dump ${TRAVIS_BUILD_DIR}/contrail-gremlin-binaries
    - cd ${TRAVIS_BUILD_DIR}/contrail-gremlin-binaries
    - git add .
    - git -c user.name='Travis' -c user.email='Travis' commit -m "contrail-gremlin commit ${COMMIT_ID}"
    - git push -f origin ${TRAVIS_BRANCH}

language: go
go:
    - 1.9.x
